const assert=require('node:assert/strict');
require('../cap-enterprise-core.js');
const C=global.CapEnterpriseCore;
let p=C.previewImport([{name:'A',__planning:true},{name:''}],'drivers');
assert.equal(p.rows,2);assert.equal(p.planning,1);assert.equal(p.invalid,1);
const events=C.workloadEventsFromPlanning([{name:'Mario Rossi',__planningEntries:[{date:'2026-08-28',value:'DOPPIO'},{date:'2026-08-29',value:'AM'}]}],[{id:'d1',name:'Mario Rossi'}],'file.xlsx');
assert.equal(events.length,1);assert.equal(events[0].event_type,'DOUBLE_SHIFT');assert.equal(events[0].source_key,'file.xlsx:d1:2026-08-28:DOUBLE_SHIFT');
const now=new Date('2026-08-28T10:00:00Z');
const tp=new Map([['r1',{route_id:'r1',tp_stage:'BLOCKED',load_ready:false,chilled_required:true,planned_departure_at:'2026-08-28T09:00:00Z'}]]);
const evidence=[{route_id:'r1',departure_temperature_c:3.4,temperature_status:'ALERT'}];
const ready=C.tpReadiness(tp,now,evidence);assert.equal(ready.blocked,1);assert.equal(ready.temp_fail,1);assert.equal(ready.load_not_ready,1);assert.equal(ready.departure_overdue,1);assert.equal(ready.cold_unverified,0);
const missing=C.tpReadiness(tp,now,[]);assert.equal(missing.temp_fail,0);assert.equal(missing.cold_unverified,1);
const snap=C.closureSnapshot({drivers:[{id:'d1',status:'assente'}],vans:[{status:'guasto'}],routes:[{id:'r1',driver_id:'d1',service_date:C.todayRome(now),status:'coperto'}],emergencies:[{is_open:true}]},{sources:[],handovers:[{status:'OPEN'}]},tp,now,evidence);
assert.equal(snap.assigned_unavailable,1);assert.equal(snap.van_issues,1);assert.equal(snap.emergencies,1);assert.equal(snap.handovers_open,1);assert.equal(snap.tp_blocked,1);assert.equal(snap.temp_fail,1);assert.equal(snap.departure_overdue,1);assert.ok(snap.critical>=6);assert.ok(C.fairnessBurden({double_30:2,extra_30:3})>0);
const report=C.reportText(snap,'CAP Delivery · Transit Point');assert.match(report,/Giri:/);assert.match(report,/alert temperatura esterna/i);assert.match(report,/Data gap:/);
console.log('PASS enterprise core guards');
