const assert=require('node:assert/strict');
const ai=require('../office/ai-core.js');
assert.equal(ai.VERSION,'8.0.0');
assert.equal(ai.__test.extractText({message:{content:'ciao'}}),'ciao');
assert.equal(ai.__test.extractText({message:{content:[{type:'text',text:'uno'},{type:'text',text:'due'}]}}),'uno\ndue');
assert.equal(ai.__test.classifyError(new Error('The API key has reached its budget')),'budget');
assert.equal(ai.__test.classifyError(new Error('request timeout')),'timeout');
assert.equal(ai.__test.isPublishableKey('sk_secret_123456'),false);
assert.equal(ai.__test.isPublishableKey('pk_public_123456'),true);
assert.match(ai.localFallback('Crea una app').text,/Modalita degradata/);
assert.equal(ai.localFallback('Crea una app').degraded,true);
assert.equal(ai.__test.verdict('VERDICT: PASS\nok'),'pass');
assert.equal(ai.__test.verdict('VERDICT: WARN\nfix'),'warn');
assert.match(ai.__test.systemPrompt('sentinel'),/sicurezza/i);
console.log('office-ai-core tests: OK');
