const assert=require('node:assert/strict');
const fs=require('node:fs');
const html=fs.readFileSync('office/index.html','utf8');
const pos=(s)=>html.indexOf(s);
assert.ok(pos('https://js.puter.com/v2/')>=0,'Puter runtime missing');
assert.ok(pos('ai-core.js')>pos('https://js.puter.com/v2/'),'ai-core must load after Puter');
assert.ok(pos('app-v8.js')>pos('ai-core.js'),'app-v8 must load after ai-core');
assert.equal(html.includes('app.js\"></script>'),false,'legacy app must not load beside V8');
const core=fs.readFileSync('office/ai-core.js','utf8');
assert.equal(/Bearer\s+sk_/.test(core),false,'secret key must not be embedded');
assert.match(core,/publishable pk_/i);
console.log('office-v8 shell tests: OK');
