const assert=require('node:assert/strict');
const fs=require('node:fs');
const index=fs.readFileSync('index.html','utf8');
const planning=fs.readFileSync('cap-planning-horizon-layer.js','utf8');
const ops=fs.readFileSync('cap-ops-layer.js','utf8');
const office=fs.readFileSync('cap-office-bridge.js','utf8');
const enterprise=fs.readFileSync('cap-enterprise-layer.js','utf8');
const live=fs.readFileSync('cap-live-status.js','utf8');
const css=fs.readFileSync('cap-live-status.css','utf8');
assert.match(index,/CAP Delivery 6\.5 · Resilience \+ Operational Clarity/);
assert.match(index,/cap-live-status\.css/);
assert.match(index,/cap-live-status\.js/);
assert.doesNotMatch(planning,/localStorage\.getItem\(['"]cap_token['"]\)/);
assert.match(planning,/sessionStorage\.getItem\(['"]cap_token['"]\)/);
assert.match(planning,/state\.routes/);
assert.match(planning,/state\.drivers/);
assert.match(planning,/LOCAL_FALLBACK_NO_BACKEND/);
assert.match(planning,/BACKEND LIVE · DATI CONFERMATI/);
assert.match(planning,/CapLiveStatus\?\.report\?\.\('planning'/);
assert.match(ops,/CapLiveStatus\?\.report\?\.\('control tower'/);
assert.match(office,/CapLiveStatus\?\.report\?\.\('office bridge'/);
assert.match(enterprise,/CapLiveStatus\?\.report\?\.\('shift control'/);
assert.match(live,/health\/ready/);
assert.match(live,/aria-live/);
assert.match(live,/MODALITÀ DEGRADATA|Modalità degradata/);
assert.match(css,/\.cap-live-status\.down/);
console.log('PASS CAP 6.5 resilience contract');
