(function(){'use strict';
var APP_VERSION='8.0';
var NAV=[['home','⌂','Home'],['chat','◌','Chat'],['projects','＋','Progetti'],['round','◎','Tavola Rotonda'],['agents','✿','Agenti'],['knowledge','▤','Knowledge'],['agenda','□','Agenda'],['results','✓','Risultati'],['audit','≣','Audit'],['settings','⚙','Impostazioni']];
var AGENTS=[
{id:'director',emoji:'🐶',name:'Director',role:'Boxer · coordina e decide',provider:'Auto',on:true},
{id:'scout',emoji:'🦮',name:'Scout',role:'Ricerca e fonti',provider:'Auto',on:true},
{id:'analyst',emoji:'🐱',name:'Analyst',role:'Dati e analisi',provider:'Auto',on:true},
{id:'skeptic',emoji:'🦉',name:'Skeptic',role:'Revisore indipendente',provider:'Anthropic',on:true},
{id:'builder',emoji:'🐻‍❄️',name:'Builder',role:'Crea e implementa',provider:'Auto',on:true},
{id:'wildcard',emoji:'🦊',name:'Wildcard',role:'Idee fuori schema',provider:'Google',on:true},
{id:'archivist',emoji:'🐢',name:'Archivist',role:'Memoria e conoscenza',provider:'Local',on:true},
{id:'sentinel',emoji:'🐕',name:'Sentinel',role:'Rottweiler · sicurezza',provider:'Anthropic',on:true}
];
var BASE={version:8,tasks:[{id:1,title:'The Office V8 resilienza AI',agent:'Builder',status:'working',p:72}],approvals:[],projects:[{id:1,name:'The Office',stage:'Build',progress:82},{id:2,name:'CAP Delivery',stage:'Operations',progress:64},{id:3,name:'Tennis Edge',stage:'Research',progress:48}],notes:[{id:1,title:'Policy V8',body:'Fallback automatico, revisione indipendente e conferma umana per azioni esterne o irreversibili.'}],events:[],results:[],audit:[],chat:[{id:1,me:false,txt:'V8 operativo. Le risposte AI reali riportano gateway, modello e stato della revisione. Se i provider falliscono, passo in modalità degradata senza fingere una risposta.',meta:'runtime V8'}],round:[],lastPrompt:'',busy:false};
function clone(x){return JSON.parse(JSON.stringify(x))}
function migrate(s){if(!s||!Array.isArray(s.tasks))s=clone(BASE);s.version=8;if(!Array.isArray(s.agents)||!s.agents.length)s.agents=clone(AGENTS);else AGENTS.forEach(function(a){if(!s.agents.some(function(x){return x.id===a.id}))s.agents.push(clone(a))});['approvals','projects','notes','events','results','audit','chat','round'].forEach(function(k){if(!Array.isArray(s[k]))s[k]=[]});s.chat=s.chat.map(function(m){if(!m.id)m.id=Date.now()+Math.random();return m});if(typeof s.busy!=='boolean')s.busy=false;if(!s.view)s.view='home';if(!s.lastPrompt)s.lastPrompt='';return s}
var state=null;try{state=JSON.parse(localStorage.getItem('theOfficeWeb')||'null')}catch(e){}state=migrate(state);state.busy=false;
function save(){try{localStorage.setItem('theOfficeWeb',JSON.stringify(state))}catch(e){}}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function nl(s){return esc(s).replace(/\n/g,'<br>')}
function toast(s){var e=document.getElementById('toast');if(!e)return;e.textContent=s;e.classList.add('show');setTimeout(function(){e.classList.remove('show')},1800)}
function log(txt){var d=new Date(),t=('0'+d.getHours()).slice(-2)+':'+('0'+d.getMinutes()).slice(-2);state.audit.unshift({t:t,txt:txt});state.audit=state.audit.slice(0,200);save()}
function getAgent(id){return state.agents.find(function(a){return a.id===id})||state.agents[0]}
function agentRoleName(id){var a=getAgent(id);return a?a.name:'Director'}
function roleProvider(id){var a=getAgent(id),p=String(a&&a.provider||'Auto');if(p==='Puter')return{gateway:'puter'};if(p==='Pollinations')return{gateway:'pollinations'};if(p==='Local')return{gateway:'local'};if(['OpenAI','Anthropic','Google','xAI'].indexOf(p)>=0)return{gateway:'auto',modelProvider:p.toLowerCase()};return{gateway:'auto'}}
function go(v){state.view=v;save();render();window.scrollTo(0,0)}window.go=go;
function nav(){var n=document.getElementById('nav'),m=document.getElementById('mobilebar');if(n)n.innerHTML=NAV.map(function(x){return '<button class="'+(state.view===x[0]?'on':'')+'" onclick="go(\''+x[0]+'\')">'+x[1]+' &nbsp; '+x[2]+'</button>'}).join('');if(m)m.innerHTML=NAV.slice(0,8).map(function(x){return '<button class="'+(state.view===x[0]?'on':'')+'" onclick="go(\''+x[0]+'\')">'+x[1]+'<br>'+x[2].split(' ')[0]+'</button>'}).join('')}
function aiStatus(){try{return window.OfficeAI?OfficeAI.status():null}catch(e){return null}}
function runtimeBadge(){var s=aiStatus();if(!s)return '<span class="pill bad">AI core assente</span>';var live=(s.puter.enabled&&s.puter.available&&!s.puter.circuitOpen)||(s.pollinations.configured&&!s.pollinations.circuitOpen);return live?'<span class="pill"><i class="dot"></i>AI pronta</span>':'<span class="pill warn">modalità degradata</span>'}
function taskItem(t){var ic=t.status==='done'?'✓':t.status==='review'?'◔':t.status==='waiting'?'◌':'●';return '<div class="item"><div class="ico">'+ic+'</div><div class="grow"><b>'+esc(t.title)+'</b><span class="small muted">'+esc(t.agent)+' · '+esc(t.status)+'</span><div class="progress"><i style="width:'+Math.max(0,Math.min(100,t.p||0))+'%"></i></div></div><button class="btn" onclick="advanceTask('+t.id+')">›</button></div>'}
function approvalItem(a){if(a.state!=='pending')return '';return '<div class="item"><div class="ico">▤</div><div class="grow"><b>'+esc(a.title)+'</b><span class="small muted">Richiesta da '+esc(a.by)+'</span></div><button class="btn" onclick="reviewApproval('+a.id+')">Rivedi</button><button class="btn good" onclick="approve('+a.id+')">Approva</button></div>'}
function home(){var seats=state.agents.map(function(a){return '<div class="seat" onclick="openAgent(\''+a.id+'\')"><div class="face">'+a.emoji+'</div><div class="plate">'+esc(a.name)+'<span>'+esc(a.role)+'</span></div></div>'}).join('');return '<div class="home"><section class="scene"><div class="mountain"></div><div class="fire"></div><div class="headline">Dalla conoscenza<br>all’impatto.<small>Agenti specializzati, fallback reali, decisioni tracciate.</small></div><div class="agents">'+seats+'</div><div class="table"></div><button class="roundbtn" onclick="go(\'round\')">TAVOLA ROTONDA<small>CONFRONTA · CONTESTA · DECIDI</small></button><div class="quick"><button onclick="go(\'chat\')">＋ Nuova richiesta</button><button onclick="go(\'round\')">◎ Tavola Rotonda</button><button onclick="quickTask(\'Analisi approfondita\',\'Analyst\')">▥ Analizza</button><button onclick="quickTask(\'Crea deliverable\',\'Builder\')">▤ Crea</button><button onclick="go(\'settings\')">⚙ Runtime AI</button></div></section><aside class="right"><div class="card"><div class="row between"><h3>Stato Ufficio</h3>'+runtimeBadge()+'</div><div class="kpis"><div class="kpi"><b>'+state.agents.filter(function(a){return a.on}).length+'</b><span class="small">Agenti</span></div><div class="kpi"><b>'+state.projects.length+'</b><span class="small">Progetti</span></div><div class="kpi"><b>'+state.tasks.filter(function(t){return t.status!=='done'}).length+'</b><span class="small">Task</span></div><div class="kpi"><b>'+state.approvals.filter(function(a){return a.state==='pending'}).length+'</b><span class="small">Approval</span></div></div></div><div class="card"><div class="row between"><h3>Task in corso</h3><button class="btn" onclick="go(\'results\')">Vedi tutti</button></div><div class="list">'+(state.tasks.slice(0,4).map(taskItem).join('')||'<p class="muted">Nessun task.</p>')+'</div></div><div class="card"><div class="row between"><h3>Approvazioni</h3><span class="pill">'+state.approvals.filter(function(a){return a.state==='pending'}).length+' in attesa</span></div><div class="list">'+(state.approvals.map(approvalItem).join('')||'<p class="muted">Nessuna approvazione in attesa.</p>')+'</div></div></aside></div>'}
function messageHtml(m){var cls='msg '+(m.me?'me':'')+(m.pending?' pending':'')+(m.degraded?' degraded':'');var meta=m.meta?'<div class="msgmeta">'+esc(m.meta)+'</div>':'';return '<div class="'+cls+'" data-msg-id="'+esc(m.id)+'">'+nl(m.txt)+(m.pending?'<span class="thinking"> •••</span>':'')+meta+'</div>'}
function chat(){return '<div class="title"><div><h1>Chat con l’ufficio</h1><p>Risposte reali quando il runtime è disponibile; fallback trasparente quando non lo è.</p></div>'+runtimeBadge()+'</div><div class="card"><div class="chat" id="chatbox">'+state.chat.map(messageHtml).join('')+'</div><div class="form" style="margin-top:12px"><textarea id="chatInput" placeholder="Dimmi cosa vuoi ottenere…" '+(state.busy?'disabled':'')+'></textarea><div class="row"><select id="chatMode" '+(state.busy?'disabled':'')+'><option value="auto">Director sceglie il team</option><option value="round">Forza Tavola Rotonda</option><option value="builder">Builder</option><option value="analyst">Analyst</option><option value="sentinel">Sentinel</option><option value="scout">Scout + web search</option></select><button class="btn primary" '+(state.busy?'disabled':'')+' onclick="sendChat()">'+(state.busy?'In esecuzione…':'Invia')+'</button></div></div></div>'}
function projects(){return '<div class="title"><div><h1>Progetti</h1><p>Obiettivi, avanzamento e milestone.</p></div><button class="btn primary" onclick="newProject()">＋ Nuovo progetto</button></div><div class="grid g3">'+state.projects.map(function(p){return '<div class="card"><span class="pill">'+esc(p.stage)+'</span><h2 style="margin-top:12px">'+esc(p.name)+'</h2><div class="progress"><i style="width:'+p.progress+'%"></i></div><p class="muted">'+p.progress+'% completato</p><button class="btn" onclick="projectStep('+p.id+')">Aggiungi milestone</button></div>'}).join('')+'</div>'}
function seedRound(){if(state.round.length)return;state.round=[{by:'Director',kind:'brief',txt:'La Tavola Rotonda V8 usa interventi indipendenti e una sintesi separata. Avvia un giro sul tema corrente.'}]}
function round(){seedRound();return '<div class="title"><div><h1>Tavola Rotonda</h1><p>Analyst, Skeptic e Wildcard lavorano separatamente; Director sintetizza dopo.</p></div><div class="row"><button class="btn" '+(state.busy?'disabled':'')+' onclick="roundTurn()">'+(state.busy?'In esecuzione…':'Nuovo giro')+'</button><button class="btn gold" onclick="roundDecision()">Trasforma decisione in task</button></div></div><div class="roundgrid"><div class="card"><h3>Partecipanti</h3>'+state.agents.filter(function(a){return a.on&&['analyst','skeptic','wildcard','director','sentinel','scout'].indexOf(a.id)>=0}).map(function(a){return '<div class="item"><div class="ico">'+a.emoji+'</div><div><b>'+esc(a.name)+'</b><span class="small muted">'+esc(a.role)+'</span></div></div>'}).join('')+'<div class="form" style="margin-top:12px"><textarea id="roundHuman" placeholder="Tema o intervento umano…"></textarea><button class="btn primary" onclick="humanRound()">Aggiungi intervento</button></div></div><div class="card"><h3>Discussione</h3>'+state.round.map(function(r){return '<div class="statement '+esc(r.kind||'')+'"><div class="row"><b>'+esc(r.by)+'</b><span class="pill">'+esc(r.kind||'punto')+'</span></div><div style="margin-top:6px">'+nl(r.txt)+'</div>'+(r.meta?'<div class="msgmeta">'+esc(r.meta)+'</div>':'')+'</div>'}).join('')+'</div></div>'}
function agents(){var options=['Auto','Puter','Pollinations','Local','OpenAI','Anthropic','Google','xAI'];return '<div class="title"><div><h1>Agenti</h1><p>Ruoli, stato e routing preferito. Auto usa fallback; Local non chiama servizi esterni.</p></div><button class="btn primary" onclick="addAgent()">＋ Agente custom</button></div><div class="agentgrid">'+state.agents.map(function(a){return '<div class="agentcard '+(a.on?'':'off')+'"><div class="row between"><div class="big">'+a.emoji+'</div><span class="pill">'+(a.on?'online':'off')+'</span></div><h2>'+esc(a.name)+'</h2><p class="muted">'+esc(a.role)+'</p><select onchange="setProvider(\''+a.id+'\',this.value)">'+options.map(function(o){return '<option '+(a.provider===o?'selected':'')+'>'+o+'</option>'}).join('')+'</select><button class="btn" style="margin-top:10px" onclick="toggleAgent(\''+a.id+'\')">'+(a.on?'Disattiva':'Attiva')+'</button></div>'}).join('')+'</div>'}
function knowledge(){return '<div class="title"><div><h1>Knowledge</h1><p>Memoria condivisa e decisioni.</p></div><button class="btn primary" onclick="newNote()">＋ Nuova nota</button></div><div class="grid g2">'+state.notes.map(function(n){return '<div class="card"><h3>'+esc(n.title)+'</h3><p>'+nl(n.body)+'</p><button class="btn" onclick="deleteNote('+n.id+')">Elimina</button></div>'}).join('')+'</div>'}
function agenda(){return '<div class="title"><div><h1>Agenda</h1><p>Attività operative e revisioni.</p></div><button class="btn primary" onclick="newEvent()">＋ Evento</button></div><div class="card"><table><tbody>'+state.events.map(function(e){return '<tr><td>'+esc(e.when)+'</td><td><b>'+esc(e.title)+'</b></td><td><button class="btn" onclick="removeEvent('+e.id+')">Chiudi</button></td></tr>'}).join('')+'</tbody></table>'+(state.events.length?'':'<p class="muted">Nessun evento.</p>')+'</div>'}
function results(){return '<div class="title"><div><h1>Risultati</h1><p>Deliverable e lavori completati.</p></div></div><div class="grid g2">'+(state.results.map(function(r){return '<div class="card"><span class="pill">'+esc(r.type)+'</span><h2>'+esc(r.title)+'</h2><p class="muted">'+esc(r.date)+'</p>'+(r.summary?'<p>'+nl(r.summary)+'</p>':'')+'<button class="btn" onclick="exportResult('+r.id+')">Esporta</button></div>'}).join('')||'<div class="card"><p class="muted">Nessun deliverable ancora.</p></div>')+'</div>'}
function audit(){return '<div class="title"><div><h1>Audit</h1><p>Registro di routing, fallback, revisioni e decisioni.</p></div><button class="btn" onclick="exportAudit()">Esporta JSON</button></div><div class="card"><table><tbody>'+state.audit.map(function(a){return '<tr><td style="width:80px">'+esc(a.t)+'</td><td>'+esc(a.txt)+'</td></tr>'}).join('')+'</tbody></table></div>'}
function healthCard(name,x,extra){var h=x&&x.health||{};var stateTxt=x&&x.circuitOpen?'circuit aperto':(x&&((x.available&&x.enabled)||x.configured)?'pronto':'non configurato');return '<div class="ai-health"><div class="row between"><b>'+esc(name)+'</b><span class="pill">'+esc(stateTxt)+'</span></div><small>'+esc(extra||'')+'</small>'+(h.lastError?'<p class="small badtxt">Ultimo errore: '+esc(h.lastKind||'')+' · '+esc(h.lastError)+'</p>':'')+(h.lastSuccess?'<p class="small muted">Ultimo successo: '+esc(h.lastSuccess)+'</p>':'')+'</div>'}
function settings(){var s=aiStatus()||{puter:{},pollinations:{},verify:true};return '<div class="title"><div><h1>Impostazioni</h1><p>Runtime AI, sicurezza e persistenza.</p></div><span class="pill">V'+APP_VERSION+'</span></div><div class="grid g2"><div class="card"><h3>Runtime AI resiliente</h3><div class="ai-health-grid">'+healthCard('Puter',s.puter,'Gateway senza chiave sviluppatore; eventuale uso AI segue il modello user-pays del provider.')+healthCard('Pollinations',s.pollinations,'Fallback opzionale. Accetto solo chiavi publishable pk_ in sessione, mai sk_.')+'</div><div class="form"><label>Pollinations publishable key (solo questa sessione)</label><input id="polliKey" type="password" autocomplete="off" placeholder="pk_…"><div class="row"><button class="btn" onclick="savePolliKey()">Salva pk_</button><button class="btn" onclick="clearPolliKey()">Rimuovi</button><button class="btn gold" onclick="testAI()">Test runtime</button></div><label><input type="checkbox" '+(s.puter&&s.puter.enabled?'checked':'')+' onchange="togglePuter(this.checked)"> Abilita Puter come gateway primario</label><label><input type="checkbox" '+(s.verify?'checked':'')+' onchange="toggleVerify(this.checked)"> Revisione indipendente automatica</label></div></div><div class="card"><h3>Safety gates</h3><p>Le risposte possono proporre azioni, ma pagamenti, cancellazioni, invii o altre azioni esterne non vengono eseguite da questa web-app senza un passaggio esplicito di approvazione.</p><p class="muted">Le chiavi segrete non vengono salvate. La chiave Pollinations publishable resta in sessionStorage e sparisce chiudendo la sessione browser.</p></div><div class="card"><h3>Dati locali</h3><p class="muted">Chat, task, audit e progetti restano nel browser.</p><button class="btn bad" onclick="resetOffice()">Reset locale</button></div><div class="card"><h3>Diagnostica</h3><p class="muted">Un provider in errore due volte viene escluso temporaneamente; gli altri continuano. Se tutti falliscono, il run termina in modalità degradata e viene registrato.</p><button class="btn" onclick="exportAudit()">Esporta audit</button></div></div>'}
function render(){nav();var f={home:home,chat:chat,projects:projects,round:round,agents:agents,knowledge:knowledge,agenda:agenda,results:results,audit:audit,settings:settings}[state.view]||home;var main=document.getElementById('main');if(main)main.innerHTML=f();if(state.view==='chat'){var c=document.getElementById('chatbox');if(c)c.scrollTop=c.scrollHeight}}window.render=render;
function history(){return state.chat.filter(function(m){return !m.pending}).slice(-10).map(function(m){return{role:m.me?'user':'assistant',content:m.txt}})}
function metaFor(res){if(!res)return 'nessun risultato';var p=res.primary||res;var bits=[p.gateway||'?',p.provider&&p.provider!=='auto'?p.provider:null,p.model||null].filter(Boolean);if(res.degraded||p.degraded)bits.push('DEGRADATO');else if(res.verified)bits.push('VERIFICATO');else if(res.review)bits.push('REVISIONE NON PASS');else bits.push('NON REVISIONATO');return bits.join(' · ')}
function roleFromMode(mode){return mode==='builder'?'builder':mode==='analyst'?'analyst':mode==='sentinel'?'sentinel':mode==='scout'?'scout':'director'}
window.openAgent=function(id){go('agents');setTimeout(function(){var a=getAgent(id);toast(a.name+' · '+a.role)},20)};
window.advanceTask=function(id){var t=state.tasks.find(function(x){return x.id===id});if(!t)return;if(t.status==='working'){t.status='review';t.p=Math.max(t.p||0,82)}else if(t.status==='review'){t.status='waiting';t.p=94;state.approvals.push({id:Date.now(),title:t.title,by:t.agent,state:'pending'})}else if(t.status==='waiting'){toast('In attesa di conferma')}else if(t.status==='done'){toast('Task completato')}log('Task aggiornato: '+t.title);save();render()};
window.approve=function(id){var a=state.approvals.find(function(x){return x.id===id});if(!a)return;a.state='approved';var t=state.tasks.find(function(x){return x.title===a.title&&x.status!=='done'});if(t){t.status='done';t.p=100}state.results.unshift({id:Date.now(),title:a.title,type:'Deliverable',date:'Adesso'});log('Confermato: '+a.title);save();render();toast('Confermato')};
window.reviewApproval=function(id){var a=state.approvals.find(function(x){return x.id===id});if(!a)return;a.state='review';log('Richiesta revisione: '+a.title);save();render();toast('Rimandato in revisione')};
window.quickTask=function(title,who){state.tasks.unshift({id:Date.now(),title:title,agent:who,status:'working',p:12});log('Creato task: '+title);save();render();toast('Task assegnato a '+who)};
window.sendChat=async function(){if(state.busy)return;var el=document.getElementById('chatInput'),modeEl=document.getElementById('chatMode'),txt=(el&&el.value||'').trim(),mode=modeEl&&modeEl.value||'auto';if(!txt)return;state.lastPrompt=txt;state.chat.push({id:Date.now(),me:true,txt:txt});var mid=Date.now()+1;state.chat.push({id:mid,me:false,txt:'Director sta orchestrando la richiesta',pending:true,meta:'checkpoint creato'});var task={id:Date.now()+2,title:txt.slice(0,70),agent:agentRoleName(roleFromMode(mode)),status:'working',p:12};state.tasks.unshift(task);state.busy=true;log('Run avviato: '+txt.slice(0,80));save();render();if(mode==='round'){state.view='round';seedRound();state.round.push({by:'Davide',kind:'human',txt:txt});save();render();await runRound(txt,task);return}try{if(!window.OfficeAI)throw new Error('OfficeAI non caricato');var role=roleFromMode(mode),routing=roleProvider(role);var res=await OfficeAI.run(txt,{role:role,history:history().slice(0,-1),gateway:routing.gateway,modelProvider:routing.modelProvider,webSearch:role==='scout'});var msg=state.chat.find(function(m){return m.id===mid});if(msg){msg.txt=res.text;msg.pending=false;msg.degraded=!!res.degraded;msg.meta=metaFor(res)}task.status='review';task.p=84;if(res.review&&!res.verified)task.p=78;state.results.unshift({id:Date.now(),title:txt.slice(0,72),type:res.degraded?'Run degradato':'AI run',date:'Adesso',summary:res.text.slice(0,420),runtime:metaFor(res)});log('Run completato · '+metaFor(res))}catch(e){var msg2=state.chat.find(function(m){return m.id===mid});if(msg2){msg2.txt='Run non completato: '+String(e&&e.message||e);msg2.pending=false;msg2.degraded=true;msg2.meta='ERRORE NON RECUPERATO'}task.status='review';task.p=40;log('Run fallito: '+String(e&&e.message||e).slice(0,120))}finally{state.busy=false;save();render()}};
async function runRound(prompt,task){state.busy=true;save();render();var checkpoint=Date.now();state.round.push({by:'Director',kind:'brief',txt:'Checkpoint '+checkpoint+': raccolgo tre interventi indipendenti prima della sintesi.',meta:'run V8'});save();render();try{if(!window.OfficeAI)throw new Error('OfficeAI non caricato');var res=await OfficeAI.round(prompt,{history:history().slice(0,-1),roles:['analyst','skeptic','wildcard']});res.entries.forEach(function(e){var a=getAgent(e.role);state.round.push({by:a?a.name:e.role,kind:e.role==='skeptic'?'dissent':e.role==='wildcard'?'idea':'analysis',txt:e.result.text,meta:e.result.gateway+' · '+e.result.model+(e.result.degraded?' · DEGRADATO':'')})});state.round.push({by:'Director',kind:'synthesis',txt:res.decision.text,meta:res.decision.gateway+' · '+res.decision.model+(res.decision.degraded?' · DEGRADATO':'')});task.status='review';task.p=res.degraded?65:88;state.results.unshift({id:Date.now(),title:'Tavola Rotonda · '+prompt.slice(0,55),type:'Decisione',date:'Adesso',summary:res.decision.text.slice(0,500)});log('Tavola Rotonda completata'+(res.degraded?' in modalità degradata':''))}catch(e){state.round.push({by:'Director',kind:'dissent',txt:'Tavola Rotonda interrotta: '+String(e&&e.message||e),meta:'errore'});task.status='review';task.p=45;log('Tavola Rotonda fallita: '+String(e&&e.message||e).slice(0,100))}finally{state.busy=false;save();render()}}
window.roundTurn=async function(){if(state.busy)return;var e=document.getElementById('roundHuman'),t=(e&&e.value||'').trim()||state.lastPrompt||'Valuta lo stato attuale del progetto e proponi il prossimo miglioramento ad alto impatto.';state.lastPrompt=t;if(e&&e.value.trim())state.round.push({by:'Davide',kind:'human',txt:t});var task={id:Date.now(),title:'Tavola Rotonda: '+t.slice(0,55),agent:'Director',status:'working',p:10};state.tasks.unshift(task);await runRound(t,task)};
window.humanRound=function(){var e=document.getElementById('roundHuman'),t=(e&&e.value||'').trim();if(!t)return;state.lastPrompt=t;state.round.push({by:'Davide',kind:'human',txt:t});log('Intervento umano in Tavola Rotonda');save();render()};
window.roundDecision=function(){var d=[].concat(state.round).reverse().find(function(x){return x.kind==='synthesis'});if(!d){toast('Prima completa un giro con sintesi');return}var title='Eseguire decisione Tavola Rotonda';state.tasks.unshift({id:Date.now(),title:title,agent:'Director',status:'review',p:85});state.approvals.unshift({id:Date.now()+1,title:title,by:'Director',state:'pending'});state.notes.unshift({id:Date.now()+2,title:'Decisione Tavola Rotonda',body:d.txt});log('Decisione trasformata in task soggetto ad approvazione');save();render();toast('Decisione pronta per approvazione')};
window.toggleAgent=function(id){var a=getAgent(id);a.on=!a.on;log((a.on?'Attivato ':'Disattivato ')+a.name);save();render()};
window.setProvider=function(id,v){var a=getAgent(id);a.provider=v;log('Routing '+a.name+': '+v);save()};
window.addAgent=function(){var n=prompt('Nome agente');if(!n)return;var r=prompt('Ruolo','Specialista')||'Specialista';state.agents.push({id:'custom'+Date.now(),emoji:'🦝',name:n,role:r,provider:'Auto',on:true});log('Aggiunto agente '+n);save();render()};
window.newProject=function(){var n=prompt('Nome progetto');if(!n)return;state.projects.unshift({id:Date.now(),name:n,stage:'Discovery',progress:5});log('Creato progetto: '+n);save();render()};window.projectStep=function(id){var p=state.projects.find(function(x){return x.id===id});if(!p)return;p.progress=Math.min(100,p.progress+10);p.stage=p.progress>=100?'Done':'Build';log('Milestone progetto: '+p.name);save();render()};
window.newNote=function(){var t=prompt('Titolo nota');if(!t)return;var b=prompt('Contenuto')||'';state.notes.unshift({id:Date.now(),title:t,body:b});log('Creata nota: '+t);save();render()};window.deleteNote=function(id){state.notes=state.notes.filter(function(n){return n.id!==id});save();render()};
window.newEvent=function(){var t=prompt('Evento');if(!t)return;var w=prompt('Quando','Oggi · 16:00')||'Da definire';state.events.unshift({id:Date.now(),when:w,title:t});log('Creato evento: '+t);save();render()};window.removeEvent=function(id){state.events=state.events.filter(function(e){return e.id!==id});save();render()};
function download(name,obj){var b=new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(function(){URL.revokeObjectURL(u)},500)}
window.exportAudit=function(){download('the-office-v8-audit.json',{version:APP_VERSION,exportedAt:new Date().toISOString(),audit:state.audit})};window.exportResult=function(id){download('the-office-v8-result.json',state.results.find(function(x){return x.id===id})||{})};
window.resetOffice=function(){if(!confirm('Resettare lo stato locale di The Office?'))return;state=migrate(clone(BASE));state.agents=clone(AGENTS);state.view='home';save();render()};
window.savePolliKey=function(){var e=document.getElementById('polliKey'),k=(e&&e.value||'').trim();try{OfficeAI.setPollinationsKey(k);if(e)e.value='';log('Configurata chiave Pollinations publishable in sessione');render();toast('Chiave pk_ configurata')}catch(err){toast(err.message||'Chiave non valida')}};
window.clearPolliKey=function(){if(window.OfficeAI)OfficeAI.clearPollinationsKey();log('Rimossa chiave Pollinations dalla sessione');render();toast('Chiave rimossa')};
window.togglePuter=function(v){if(window.OfficeAI)OfficeAI.setPrefs({puter:!!v});log('Puter '+(v?'abilitato':'disabilitato'));render()};
window.toggleVerify=function(v){if(window.OfficeAI)OfficeAI.setPrefs({verify:!!v});log('Revisione indipendente '+(v?'abilitata':'disabilitata'));render()};
window.testAI=async function(){if(!window.OfficeAI){toast('AI core non caricato');return}toast('Test runtime avviato');try{var r=await OfficeAI.test();log('Test AI: '+(r.ok?'OK':'fallback')+' · '+r.result.gateway+' · '+r.result.model);render();toast(r.ok?'Runtime AI OK':'Runtime in modalità degradata')}catch(e){log('Test AI fallito: '+String(e&&e.message||e));render();toast('Test non riuscito')}};
var theme=document.getElementById('themeBtn');if(theme)theme.onclick=function(){document.body.style.filter=document.body.style.filter?'':'saturate(.9) brightness(.94)';toast('Tema aggiornato')};var search=document.getElementById('globalSearch');if(search)search.addEventListener('keydown',function(e){if(e.key!=='Enter')return;var q=this.value.trim();var l=q.toLowerCase();if(l.indexOf('tavola')>=0)go('round');else if(l.indexOf('agent')>=0)go('agents');else if(l.indexOf('progett')>=0)go('projects');else if(l.indexOf('know')>=0)go('knowledge');else{go('chat');setTimeout(function(){var x=document.getElementById('chatInput');if(x)x.value=q},20)}});
log('The Office V'+APP_VERSION+' avviato');render();
})();
