(function(){'use strict';
const NAV=[['home','⌂','Home'],['chat','◌','Chat'],['round','◎','Tavola'],['work','◫','Lavori'],['agents','✿','Agenti'],['results','◆','Risultati'],['improve','↗','Migliora'],['audit','≣','Audit'],['settings','⚙','Impostazioni']];
let engine={ok:false,checking:true,error:null};
const S=()=>OfficeState.get();
const e=s=>String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const nl=s=>e(s).replace(/\n/g,'<br>');
function toast(t,bad){let x=document.getElementById('toast');if(!x)return;x.textContent=t;x.classList.toggle('bad',!!bad);x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
function statusLabel(){if(engine.checking)return '<span class="v8status wait">● verifica…</span>';if(engine.ok)return '<span class="v8status ok">● AI reale online</span>';return '<span class="v8status bad">● AI offline</span>'}
async function checkEngine(renderAfter){engine.checking=true;if(renderAfter)render();const h=await OfficeAPI.health();engine={ok:h.ok,checking:false,error:h.error||(!h.gateway?'AI Gateway non configurato':null)};if(renderAfter)render();return h}
function go(v){S().view=v;OfficeState.save();render();window.scrollTo(0,0)} window.go=go;
function nav(){const d=document.getElementById('nav'),m=document.getElementById('mobilebar');if(d)d.innerHTML=NAV.map(n=>`<button class="${S().view===n[0]?'on':''}" onclick="go('${n[0]}')">${n[1]} &nbsp; ${n[2]}</button>`).join('');if(m)m.innerHTML=[['home','⌂','Home'],['chat','◌','Chat'],['round','◎','Tavola'],['work','◫','Lavori'],['more','•••','Altro']].map(n=>`<button class="${S().view===n[0]?'on':''}" onclick="${n[0]==='more'?'openMore()':`go('${n[0]}')`}">${n[1]}<br>${n[2]}</button>`).join('')}
function agentChip(a){return `<button class="v8agent-chip" onclick="openAgent('${a.id}')"><span>${a.emoji}</span><b>${e(a.name)}</b><small>${e(a.animal)}</small></button>`}
function taskRow(t){const icon=t.status==='done'?'✓':t.status==='error'?'!':t.status==='approval'?'?':'●';return `<div class="v8task"><div class="v8task-icon ${e(t.status)}">${icon}</div><div class="grow"><div class="row between"><b>${e(t.title)}</b><span class="pill">${e(t.status)}</span></div><small>${e(t.detail||t.owner)}</small><div class="progress"><i style="width:${Math.max(0,Math.min(100,t.progress||0))}%"></i></div></div>${t.runId?`<button class="btn mini" onclick="openRun('${t.runId}')">Apri</button>`:''}</div>`}
function approvalRow(a){if(a.state!=='pending')return '';return `<div class="v8approval"><div><b>${e(a.title)}</b><small>${e(a.reason)}</small></div><div class="row"><button class="btn" onclick="rejectApproval('${a.id}')">Rifiuta</button><button class="btn good" onclick="approveAction('${a.id}')">Approva</button></div></div>`}
function home(){const st=S(),running=st.tasks.filter(x=>!['done','error'].includes(x.status)).slice(0,5),aps=st.approvals.filter(x=>x.state==='pending').slice(0,3);return `<section class="v8hero"><div class="v8hero-head"><div><span class="eyebrow">THE OFFICE · V8</span><h1>Che cosa deve fare oggi l’ufficio?</h1><p>Assegna un obiettivo. Director sceglie il team, gli agenti lavorano davvero e tu controlli tutto.</p></div>${statusLabel()}</div><div class="v8command"><textarea id="homePrompt" placeholder="Es. Analizza i competitor di The Office e proponi 5 miglioramenti concreti…"></textarea><button onclick="submitHome()">Avvia</button></div><div class="v8quick"><button onclick="preset(&quot;Analizza questo problema, confronta le alternative e dammi una raccomandazione verificabile&quot;)">Analizza</button><button onclick="preset(&quot;Crea un piano operativo con priorità, rischi e prossimi passi&quot;)">Pianifica</button><button onclick="go('round')">Tavola Rotonda</button><button onclick="go('improve')">Migliora The Office</button></div></section><section class="v8agents-rail">${st.agents.filter(a=>a.on).map(agentChip).join('')}</section><div class="v8homegrid"><div class="card"><div class="row between"><h3>Lavori in corso</h3><button class="btn" onclick="go('work')">Vedi tutti</button></div>${running.length?running.map(taskRow).join(''):'<div class="empty">Nessun lavoro in corso. Assegna il primo incarico.</div>'}</div><div class="card"><div class="row between"><h3>Approvazioni</h3><span class="pill">${aps.length} in attesa</span></div>${aps.length?aps.map(approvalRow).join(''):'<div class="empty">Niente da approvare.</div>'}</div></div><div class="v8homegrid"><div class="card"><h3>Ultimi risultati</h3>${st.results.slice(0,3).map(r=>`<button class="v8result-mini" onclick="openResult('${r.id}')"><span><b>${e(r.title)}</b><small>${new Date(r.at).toLocaleString('it-IT')}</small></span><span>›</span></button>`).join('')||( '<div class="empty">I deliverable reali compariranno qui.</div>')}</div><div class="card"><h3>Regola dell’ufficio</h3><p class="muted">Nessun agente può dichiarare completata un’azione esterna che non è stata realmente eseguita. Pagamenti, invii, cancellazioni e deploy richiedono approvazione.</p></div></div>`}
function chat(){const st=S();return `<div class="title"><div><h1>Chat con Director</h1><p>Ogni invio avvia un lavoro reale dell’ufficio.</p></div>${statusLabel()}</div><div class="card"><div class="chat v8chat" id="chatbox">${st.chat.map(x=>`<div class="v8msg ${x.me?'me':''} ${x.error?'error':''}"><b>${e(x.by)}</b><div>${nl(x.txt)}</div></div>`).join('')}</div><div class="v8chatinput"><textarea id="chatInput" placeholder="Scrivi l’incarico…"></textarea><select id="chatTeam"><option value="auto">Director sceglie il team</option><option value="research">Ricerca + Analisi + Skeptic</option><option value="build">Builder + Skeptic + Sentinel</option></select><button id="chatSend" onclick="sendChat()">Invia</button></div></div>`}
function round(){const latest=S().round[0];return `<div class="title"><div><h1>Tavola Rotonda</h1><p>Gli agenti rispondono in parallelo; Director sintetizza il dissenso.</p></div>${statusLabel()}</div><div class="card v8roundstart"><textarea id="roundTopic" placeholder="Tema della discussione…">${e(latest&&latest.status==='running'?latest.topic:'')}</textarea><button class="btn primary" onclick="startRound()">Avvia Tavola Rotonda reale</button></div>${renderRound(latest)}`}
function renderRound(rt){if(!rt)return '<div class="empty big">Nessuna Tavola Rotonda ancora.</div>';return `<div class="v8round"><div class="card"><div class="row between"><h3>${e(rt.topic)}</h3><span class="pill">${e(rt.status)}</span></div>${rt.turns.map(t=>`<div class="statement ${t.final?'final':''} ${t.error?'error':''}"><div class="row between"><b>${e(t.by)}</b><small>${e(t.model||'')}</small></div><div>${nl(t.text)}</div></div>`).join('')}${rt.status==='running'?'<div class="v8working">Gli agenti stanno discutendo…</div>':''}</div></div>`}
function work(){const st=S();return `<div class="title"><div><h1>Lavori</h1><p>Stato reale di ogni run.</p></div><button class="btn primary" onclick="go('home')">＋ Nuovo lavoro</button></div><div class="card">${st.tasks.length?st.tasks.map(taskRow).join(''):'<div class="empty big">Nessun lavoro ancora.</div>'}</div>`}
function agents(){const st=S();return `<div class="title"><div><h1>Agenti</h1><p>Ruolo, modello e stato operativo.</p></div></div><div class="v8agentlist">${st.agents.map(a=>`<div class="v8agentrow ${a.on?'':'off'}"><div class="v8avatar">${a.emoji}</div><div class="grow"><div class="row"><h3>${e(a.name)}</h3><span class="pill">${e(a.animal)}</span></div><p>${e(a.role)}</p><small>Modello: ${e(OfficeAPI.MODEL[a.id]||'gpt-5-mini')}</small></div><button class="btn" onclick="toggleAgent('${a.id}')">${a.on?'Attivo':'Off'}</button></div>`).join('')}</div>`}
function results(){const st=S();return `<div class="title"><div><h1>Risultati</h1><p>Solo deliverable prodotti da run reali.</p></div></div><div class="v8results">${st.results.length?st.results.map(r=>`<button class="card v8resultcard" onclick="openResult('${r.id}')"><div class="row between"><span class="pill">${e(r.type||'AI deliverable')}</span><small>${new Date(r.at).toLocaleString('it-IT')}</small></div><h3>${e(r.title)}</h3><p>${e(r.body).slice(0,240)}${r.body.length>240?'…':''}</p></button>`).join(''):'<div class="empty big">Nessun risultato reale ancora.</div>'}</div>`}
function improve(){const im=S().improve;return `<div class="title"><div><h1>Improve The Office</h1><p>Ciclo reale di revisione del prodotto, con approvazione umana.</p></div><span class="pill">${im.cycles} cicli</span></div><div class="card"><h3>Come lavora</h3><p>Scout confronta pattern noti dei competitor, Analyst valuta, Skeptic contesta, Builder propone. Director sintetizza. Dove servono dati web aggiornati, il report deve dichiararlo.</p><button class="btn gold" id="improveBtn" onclick="runImprove()">Avvia ciclo reale</button></div><div class="v8results">${im.proposals.map(p=>`<div class="card"><div class="row between"><h3>${e(p.title)}</h3><span class="pill">${e(p.status)}</span></div><div class="v8pre">${nl(p.body)}</div></div>`).join('')||'<div class="empty big">Nessun ciclo eseguito.</div>'}</div>`}
function audit(){const st=S();return `<div class="title"><div><h1>Audit</h1><p>Registro locale di task, run, errori e approvazioni.</p></div><button class="btn" onclick="exportAudit()">Esporta JSON</button></div><div class="card"><div class="v8audit">${st.audit.map(a=>`<div><time>${e(a.time||new Date(a.at).toLocaleTimeString('it-IT'))}</time><span class="pill">${e(a.kind||'info')}</span><p>${e(a.txt)}</p></div>`).join('')}</div></div>`}
function settings(){return `<div class="title"><div><h1>Impostazioni</h1><p>Motore, limiti e sicurezza.</p></div>${statusLabel()}</div><div class="grid g2"><div class="card"><h3>Backend reale</h3><p class="small muted">Neon Function + Neon AI Gateway. Nessuna API key nel browser.</p><code class="v8code">${e(OfficeAPI.BASE)}</code><button class="btn" onclick="testBackend()">Test connessione</button></div><div class="card"><h3>Autonomia</h3><label>Massimo agenti per run</label><select onchange="setMaxAgents(this.value)"><option ${S().settings.maxAgents===2?'selected':''}>2</option><option ${S().settings.maxAgents===3?'selected':''}>3</option><option ${S().settings.maxAgents===4?'selected':''}>4</option></select><p class="small muted">Azioni esterne/irreversibili restano bloccate all’approval gate.</p></div><div class="card"><h3>Dati locali V8</h3><p class="small muted">Stato dei run e risultati salvato sul dispositivo.</p><button class="btn bad" onclick="resetV8()">Reset V8</button></div></div>`}
function render(){nav();const fn={home,chat,round,work,agents,results,improve,audit,settings}[S().view]||home,main=document.getElementById('main');main.innerHTML=fn();if(S().view==='chat'){let c=document.getElementById('chatbox');if(c)c.scrollTop=c.scrollHeight}}
async function executePrompt(text){if(!text.trim())return;OfficeState.chat('Davide',text,true);OfficeState.chat('Director','Incarico ricevuto. Sto formando il team e avviando il run reale.',false);S().view='chat';OfficeState.save();render();try{const res=await OfficeAPI.runTask(text,{onUpdate:()=>render()});OfficeState.chat('Director',res.body,false,{resultId:res.id});render();toast('Lavoro completato')}catch(err){OfficeState.chat('Sistema','Errore reale: '+err.message,false,{error:true});OfficeState.audit('Errore esecuzione: '+err.message,'error');render();toast(err.message,true)}}
window.submitHome=()=>{let x=document.getElementById('homePrompt');if(x)executePrompt(x.value)};window.preset=t=>{let x=document.getElementById('homePrompt');if(x){x.value=t;x.focus()}};
window.sendChat=()=>{let x=document.getElementById('chatInput'),sel=document.getElementById('chatTeam');if(!x)return;let team=null;if(sel&&sel.value==='research')team=['scout','analyst','skeptic'];if(sel&&sel.value==='build')team=['builder','skeptic','sentinel'];let text=x.value.trim();if(!text)return;OfficeState.chat('Davide',text,true);OfficeState.chat('Director','Avvio il team reale.',false);render();OfficeAPI.runTask(text,{team,onUpdate:()=>render()}).then(r=>{OfficeState.chat('Director',r.body,false,{resultId:r.id});render();toast('Completato')}).catch(err=>{OfficeState.chat('Sistema','Errore reale: '+err.message,false,{error:true});render();toast(err.message,true)})};
window.startRound=()=>{let x=document.getElementById('roundTopic'),t=x&&x.value.trim();if(!t)return;OfficeAPI.roundTable(t,{onUpdate:()=>render()}).then(()=>{render();toast('Tavola Rotonda completata')}).catch(err=>{toast(err.message,true);render()})};
window.runImprove=()=>{let b=document.getElementById('improveBtn');if(b)b.disabled=true;OfficeAPI.improve({onUpdate:()=>render()}).then(()=>{render();toast('Ciclo completato')}).catch(err=>{toast(err.message,true);render()})};
window.openResult=id=>{const r=S().results.find(x=>x.id===id);if(!r)return;openSheet(`<div class="row between"><h2>${e(r.title)}</h2><span class="pill">${e(r.status||r.type)}</span></div><div class="v8pre">${nl(r.body)}</div>`)};
window.openRun=id=>{const r=S().runs.find(x=>x.id===id);if(!r)return;openSheet(`<h2>${e(r.title)}</h2><div class="v8timeline">${r.events.map(x=>`<div><b>${e((OfficeState.agent(x.agentId)||{}).name||x.agentId)}</b><span>${e(x.status)}</span><p>${e(x.text)}</p></div>`).join('')}</div>${r.final?`<h3>Deliverable</h3><div class="v8pre">${nl(r.final)}</div>`:''}${r.error?`<div class="errorbox">${e(r.error)}</div>`:''}`)};
window.openAgent=id=>{go('agents');setTimeout(()=>{let a=OfficeState.agent(id);toast(a.name+' · '+a.role)},20)};
window.toggleAgent=id=>{let a=OfficeState.agent(id);a.on=!a.on;OfficeState.audit((a.on?'Attivato ':'Disattivato ')+a.name,'agent');OfficeState.save();render()};
window.approveAction=id=>{let a=S().approvals.find(x=>x.id===id);if(!a)return;a.state='approved';a.decidedAt=OfficeState.now();OfficeState.audit('Approvato: '+a.title,'approval');OfficeState.save();render();toast('Approvato. Nessuna azione esterna viene eseguita automaticamente.')};
window.rejectApproval=id=>{let a=S().approvals.find(x=>x.id===id);if(!a)return;a.state='rejected';a.decidedAt=OfficeState.now();OfficeState.audit('Rifiutato: '+a.title,'approval');OfficeState.save();render()};
window.testBackend=async()=>{let h=await checkEngine(false);toast(h.ok?'Backend e AI Gateway online':(h.error||'Gateway non disponibile'),!h.ok);render()};
window.setMaxAgents=v=>{S().settings.maxAgents=Number(v);OfficeState.save();toast('Limite aggiornato')};
window.resetV8=()=>{if(confirm('Azzerare lavori, risultati e audit V8 su questo dispositivo?')){OfficeState.reset();render();checkEngine(true)}};
window.exportAudit=()=>{let b=new Blob([JSON.stringify(S().audit,null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='the-office-v8-audit.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),500)};
function ensureSheet(){if(document.getElementById('v8sheet'))return;let back=document.createElement('div');back.id='v8back';back.className='v8back';back.onclick=closeSheet;let sh=document.createElement('aside');sh.id='v8sheet';sh.className='v8sheet';document.body.append(back,sh)}
function openSheet(html){ensureSheet();document.getElementById('v8sheet').innerHTML='<div class="v8handle"></div>'+html;document.getElementById('v8sheet').classList.add('on');document.getElementById('v8back').classList.add('on')}
function closeSheet(){let s=document.getElementById('v8sheet'),b=document.getElementById('v8back');if(s)s.classList.remove('on');if(b)b.classList.remove('on')} window.closeSheet=closeSheet;
window.openMore=()=>openSheet('<h2>Altro</h2><div class="v8more"><button onclick="go(\'agents\');closeSheet()">✿ Agenti</button><button onclick="go(\'results\');closeSheet()">◆ Risultati</button><button onclick="go(\'improve\');closeSheet()">↗ Migliora</button><button onclick="go(\'audit\');closeSheet()">≣ Audit</button><button onclick="go(\'settings\');closeSheet()">⚙ Impostazioni</button></div>');
const theme=document.getElementById('themeBtn');if(theme)theme.onclick=()=>document.body.classList.toggle('v8dim');
render();checkEngine(true);
})();