(function(){'use strict';
var NAV=[['home','⌂','Home'],['chat','◌','Chat'],['projects','＋','Progetti'],['round','◎','Tavola Rotonda'],['agents','✿','Agenti'],['knowledge','▤','Knowledge'],['agenda','□','Agenda'],['results','✓','Risultati'],['audit','≣','Audit'],['settings','⚙','Impostazioni']];
var AGENTS=[
{id:'director',emoji:'🐶',name:'Director',role:'Boxer · coordina e decide',provider:'Auto',on:true},
{id:'scout',emoji:'🦮',name:'Scout',role:'Ricerca e fonti',provider:'Web',on:true},
{id:'analyst',emoji:'🐱',name:'Analyst',role:'Dati e analisi',provider:'Auto',on:true},
{id:'skeptic',emoji:'🦉',name:'Skeptic',role:'Dubbi e qualità',provider:'Auto',on:true},
{id:'builder',emoji:'🐻‍❄️',name:'Builder',role:'Crea e implementa',provider:'Auto',on:true},
{id:'wildcard',emoji:'🦊',name:'Wildcard',role:'Idee fuori schema',provider:'Auto',on:true},
{id:'archivist',emoji:'🐢',name:'Archivist',role:'Memoria e conoscenza',provider:'Local',on:true},
{id:'sentinel',emoji:'🐕',name:'Sentinel',role:'Rottweiler · sicurezza',provider:'Auto',on:true}
];
var BASE={tasks:[{id:1,title:'Analisi mercato AI',agent:'Analyst',status:'done',p:100},{id:2,title:'Strategia lancio Q1',agent:'Builder',status:'working',p:62},{id:3,title:'Revisione documento',agent:'Skeptic',status:'review',p:78},{id:4,title:'Ricerca competitor',agent:'Scout',status:'done',p:100}],approvals:[{id:1,title:'Piano strategico Q1',by:'Director',state:'pending'},{id:2,title:'Budget marketing',by:'Analyst',state:'pending'}],projects:[{id:1,name:'The Office',stage:'Build',progress:72},{id:2,name:'CAP Delivery',stage:'Operations',progress:64},{id:3,name:'Tennis Edge',stage:'Research',progress:48}],notes:[{id:1,title:'Decisioni architetturali',body:'Frontend leggero, routing locale e conferma umana prima delle azioni esterne.'},{id:2,title:'Regole Tavola Rotonda',body:'Dissenso obbligatorio, verifica fonti, sintesi del Director e decision ledger.'}],events:[{id:1,when:'Oggi · 09:30',title:'Review Office'},{id:2,when:'Oggi · 16:00',title:'Tavola Rotonda'},{id:3,when:'Domani · 08:45',title:'CAP Daily'}],results:[{id:1,title:'Analisi mercato AI',type:'Report',date:'Oggi'},{id:2,title:'Piano lancio Q1',type:'Strategy',date:'Ieri'}],audit:[{t:'00:40',txt:'The Office avviato'},{t:'00:40',txt:'Stato locale caricato'}],chat:[{me:false,txt:'Sono operativo. Dimmi cosa vuoi ottenere: scelgo il team minimo necessario e ti mostro cosa succede.'}],round:[]};
function clone(x){return JSON.parse(JSON.stringify(x))}
var state=null;try{state=JSON.parse(localStorage.getItem('theOfficeWeb')||'null')}catch(e){}
if(!state||!state.tasks){state=clone(BASE);state.agents=clone(AGENTS);state.view='home'}
if(!state.agents)state.agents=clone(AGENTS);if(!state.view)state.view='home';
function save(){try{localStorage.setItem('theOfficeWeb',JSON.stringify(state))}catch(e){}}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function toast(s){var e=document.getElementById('toast');e.textContent=s;e.classList.add('show');setTimeout(function(){e.classList.remove('show')},1500)}
function log(txt){var d=new Date(),t=('0'+d.getHours()).slice(-2)+':'+('0'+d.getMinutes()).slice(-2);state.audit.unshift({t:t,txt:txt});state.audit=state.audit.slice(0,100);save()}
function getAgent(id){for(var i=0;i<state.agents.length;i++)if(state.agents[i].id===id)return state.agents[i];return state.agents[0]}
function go(v){state.view=v;save();render();window.scrollTo(0,0)}window.go=go;
function nav(){document.getElementById('nav').innerHTML=NAV.map(function(n){return '<button class="'+(state.view===n[0]?'on':'')+'" onclick="go(\''+n[0]+'\')">'+n[1]+' &nbsp; '+n[2]+'</button>'}).join('');document.getElementById('mobilebar').innerHTML=NAV.slice(0,8).map(function(n){return '<button class="'+(state.view===n[0]?'on':'')+'" onclick="go(\''+n[0]+'\')">'+n[1]+'<br>'+n[2].split(' ')[0]+'</button>'}).join('')}
function taskItem(t){var ic=t.status==='done'?'✓':t.status==='review'?'◔':'●';return '<div class="item"><div class="ico">'+ic+'</div><div class="grow"><b>'+esc(t.title)+'</b><span class="small muted">'+esc(t.agent)+' · '+esc(t.status)+'</span><div class="progress"><i style="width:'+t.p+'%"></i></div></div><button class="btn" onclick="advanceTask('+t.id+')">›</button></div>'}
function approvalItem(a){if(a.state!=='pending')return '';return '<div class="item"><div class="ico">▤</div><div class="grow"><b>'+esc(a.title)+'</b><span class="small muted">Richiesta da '+esc(a.by)+'</span></div><button class="btn" onclick="reviewApproval('+a.id+')">Rivedi</button><button class="btn good" onclick="approve('+a.id+')">Approva</button></div>'}
function home(){var seats=state.agents.map(function(a){return '<div class="seat" onclick="openAgent(\''+a.id+'\')"><div class="face">'+a.emoji+'</div><div class="plate">'+a.name+'<span>'+a.role+'</span></div></div>'}).join('');return '<div class="home"><section class="scene"><div class="mountain"></div><div class="fire"></div><div class="headline">Dalla conoscenza<br>all’impatto.<small>Agenti specializzati, un’unica squadra.</small></div><div class="agents">'+seats+'</div><div class="table"></div><button class="roundbtn" onclick="go(\'round\')">TAVOLA ROTONDA<small>CONFRONTA · ANALIZZA · DECIDI</small></button><div class="quick"><button onclick="go(\'chat\')">＋ Nuova richiesta</button><button onclick="go(\'round\')">◎ Tavola Rotonda</button><button onclick="quickTask(\'Analisi approfondita\',\'Analyst\')">▥ Analizza</button><button onclick="quickTask(\'Crea deliverable\',\'Builder\')">▤ Crea</button><button onclick="go(\'projects\')">□ Progetti</button></div></section><aside class="right"><div class="card"><div class="row between"><h3>Stato Ufficio</h3><span class="pill"><i class="dot"></i>Operativo</span></div><div class="kpis"><div class="kpi"><b>'+state.agents.filter(function(a){return a.on}).length+'</b><span class="small">Agenti</span></div><div class="kpi"><b>'+state.projects.length+'</b><span class="small">Progetti</span></div><div class="kpi"><b>'+state.tasks.filter(function(t){return t.status!=='done'}).length+'</b><span class="small">Task</span></div><div class="kpi"><b>'+state.approvals.filter(function(a){return a.state==='pending'}).length+'</b><span class="small">Approval</span></div></div></div><div class="card"><div class="row between"><h3>Task in corso</h3><button class="btn" onclick="go(\'results\')">Vedi tutti</button></div><div class="list">'+state.tasks.slice(0,4).map(taskItem).join('')+'</div></div><div class="card"><div class="row between"><h3>Approvazioni</h3><span class="pill">'+state.approvals.filter(function(a){return a.state==='pending'}).length+' in attesa</span></div><div class="list">'+(state.approvals.map(approvalItem).join('')||'<p class="muted">Nessuna approvazione in attesa.</p>')+'</div></div></aside></div>'}
function chat(){return '<div class="title"><div><h1>Chat con l’ufficio</h1><p>Parla con Director o assegna direttamente il lavoro.</p></div></div><div class="card"><div class="chat" id="chatbox">'+state.chat.map(function(m){return '<div class="msg '+(m.me?'me':'')+'">'+esc(m.txt)+'</div>'}).join('')+'</div><div class="form" style="margin-top:12px"><textarea id="chatInput" placeholder="Dimmi cosa vuoi ottenere…"></textarea><div class="row"><select id="chatMode"><option value="auto">Director sceglie il team</option><option value="round">Forza Tavola Rotonda</option><option value="builder">Builder</option><option value="analyst">Analyst</option><option value="sentinel">Sentinel</option></select><button class="btn primary" onclick="sendChat()">Invia</button></div></div></div>'}
function projects(){return '<div class="title"><div><h1>Progetti</h1><p>Obiettivi, avanzamento e milestone.</p></div><button class="btn primary" onclick="newProject()">＋ Nuovo progetto</button></div><div class="grid g3">'+state.projects.map(function(p){return '<div class="card"><span class="pill">'+esc(p.stage)+'</span><h2 style="margin-top:12px">'+esc(p.name)+'</h2><div class="progress"><i style="width:'+p.progress+'%"></i></div><p class="muted">'+p.progress+'% completato</p><button class="btn" onclick="projectStep('+p.id+')">Aggiungi milestone</button></div>'}).join('')+'</div>'}
function seedRound(){state.round=[{by:'Director',kind:'brief',txt:'Obiettivo: trovare la soluzione migliore, non il consenso più facile.'},{by:'Scout',kind:'evidence',txt:'Raccolgo fonti, vincoli e segnali utili alla decisione.'},{by:'Analyst',kind:'analysis',txt:'Confronterò opzioni, costi, impatto e probabilità di successo.'},{by:'Skeptic',kind:'dissent',txt:'Cerco cosa potrebbe essere sbagliato, fragile o troppo ottimistico.'},{by:'Sentinel',kind:'verify',txt:'Controllo sicurezza, permessi e passaggi delicati.'}]}
function round(){if(!state.round.length)seedRound();return '<div class="title"><div><h1>Tavola Rotonda</h1><p>Gli agenti discutono, dissentono, verificano e sintetizzano.</p></div><div class="row"><button class="btn" onclick="roundTurn()">Secondo giro</button><button class="btn gold" onclick="roundDecision()">Chiudi con decisione</button></div></div><div class="roundgrid"><div class="card"><h3>Partecipanti</h3>'+state.agents.filter(function(a){return a.on}).map(function(a){return '<div class="item"><div class="ico">'+a.emoji+'</div><div><b>'+a.name+'</b><span class="small muted">'+a.role+'</span></div></div>'}).join('')+'<div class="form" style="margin-top:12px"><textarea id="roundHuman" placeholder="Intervieni nella discussione…"></textarea><button class="btn primary" onclick="humanRound()">Aggiungi intervento</button></div></div><div class="card"><h3>Discussione live</h3>'+state.round.map(function(r){return '<div class="statement '+esc(r.kind||'')+'"><div class="row"><b>'+esc(r.by)+'</b><span class="pill">'+esc(r.kind||'punto')+'</span></div><div style="margin-top:6px">'+esc(r.txt)+'</div></div>'}).join('')+'</div></div>'}
function agents(){return '<div class="title"><div><h1>Agenti</h1><p>Ruoli, stato e provider.</p></div><button class="btn primary" onclick="addAgent()">＋ Agente custom</button></div><div class="agentgrid">'+state.agents.map(function(a){return '<div class="agentcard '+(a.on?'':'off')+'"><div class="row between"><div class="big">'+a.emoji+'</div><span class="pill">'+(a.on?'online':'off')+'</span></div><h2>'+a.name+'</h2><p class="muted">'+a.role+'</p><select onchange="setProvider(\''+a.id+'\',this.value)"><option '+(a.provider==='Auto'?'selected':'')+'>Auto</option><option '+(a.provider==='Web'?'selected':'')+'>Web</option><option '+(a.provider==='Local'?'selected':'')+'>Local</option><option>OpenAI</option><option>Anthropic</option><option>Google</option><option>xAI</option></select><button class="btn" style="margin-top:10px" onclick="toggleAgent(\''+a.id+'\')">'+(a.on?'Disattiva':'Attiva')+'</button></div>'}).join('')+'</div>'}
function knowledge(){return '<div class="title"><div><h1>Knowledge</h1><p>Memoria condivisa e decisioni.</p></div><button class="btn primary" onclick="newNote()">＋ Nuova nota</button></div><div class="grid g2">'+state.notes.map(function(n){return '<div class="card"><h3>'+esc(n.title)+'</h3><p>'+esc(n.body)+'</p><button class="btn" onclick="deleteNote('+n.id+')">Elimina</button></div>'}).join('')+'</div>'}
function agenda(){return '<div class="title"><div><h1>Agenda</h1><p>Attività operative e revisioni.</p></div><button class="btn primary" onclick="newEvent()">＋ Evento</button></div><div class="card"><table><tbody>'+state.events.map(function(e){return '<tr><td>'+esc(e.when)+'</td><td><b>'+esc(e.title)+'</b></td><td><button class="btn" onclick="removeEvent('+e.id+')">Chiudi</button></td></tr>'}).join('')+'</tbody></table></div>'}
function results(){return '<div class="title"><div><h1>Risultati</h1><p>Deliverable e lavori completati.</p></div></div><div class="grid g2">'+state.results.map(function(r){return '<div class="card"><span class="pill">'+esc(r.type)+'</span><h2>'+esc(r.title)+'</h2><p class="muted">'+esc(r.date)+'</p><button class="btn" onclick="exportResult('+r.id+')">Esporta</button></div>'}).join('')+'</div>'}
function audit(){return '<div class="title"><div><h1>Audit</h1><p>Registro delle attività.</p></div><button class="btn" onclick="exportAudit()">Esporta JSON</button></div><div class="card"><table><tbody>'+state.audit.map(function(a){return '<tr><td style="width:80px">'+esc(a.t)+'</td><td>'+esc(a.txt)+'</td></tr>'}).join('')+'</tbody></table></div>'}
function settings(){return '<div class="title"><div><h1>Impostazioni</h1><p>Policy e persistenza.</p></div></div><div class="grid g2"><div class="card"><h3>Autonomia</h3><select><option>Conservativa</option><option selected>Bilanciata</option><option>Alta</option></select><p class="muted">I passaggi delicati restano soggetti a conferma umana.</p></div><div class="card"><h3>Dati locali</h3><p class="muted">Questa versione salva lo stato nel browser.</p><button class="btn bad" onclick="resetOffice()">Reset locale</button></div></div>'}
function render(){nav();var f={home:home,chat:chat,projects:projects,round:round,agents:agents,knowledge:knowledge,agenda:agenda,results:results,audit:audit,settings:settings}[state.view]||home;document.getElementById('main').innerHTML=f();if(state.view==='chat'){var c=document.getElementById('chatbox');if(c)c.scrollTop=c.scrollHeight}}window.render=render;
window.openAgent=function(id){go('agents');setTimeout(function(){var a=getAgent(id);toast(a.name+' · '+a.role)},20)};
window.advanceTask=function(id){var t=state.tasks.find(function(x){return x.id===id});if(!t)return;if(t.status==='working'){t.status='review';t.p=82}else if(t.status==='review'){t.status='waiting';t.p=94;state.approvals.push({id:Date.now(),title:t.title,by:t.agent,state:'pending'})}else if(t.status==='done'){toast('Task completato')}else{toast('In attesa di conferma')}log('Task aggiornato: '+t.title);save();render()};
window.approve=function(id){var a=state.approvals.find(function(x){return x.id===id});if(!a)return;a.state='approved';state.results.unshift({id:Date.now(),title:a.title,type:'Deliverable',date:'Adesso'});log('Confermato: '+a.title);save();render();toast('Confermato')};
window.reviewApproval=function(id){var a=state.approvals.find(function(x){return x.id===id});if(!a)return;a.state='review';log('Richiesta revisione: '+a.title);save();render();toast('Rimandato in revisione')};
window.quickTask=function(title,who){state.tasks.unshift({id:Date.now(),title:title,agent:who,status:'working',p:12});log('Creato task: '+title);save();render();toast('Task assegnato a '+who)};
window.sendChat=function(){var el=document.getElementById('chatInput'),mode=document.getElementById('chatMode'),txt=(el.value||'').trim();if(!txt)return;state.chat.push({me:true,txt:txt});var team=/ricerc|mercato|font/i.test(txt)?'Scout + Analyst + Skeptic':/crea|costru|codice|app/i.test(txt)?'Builder + Sentinel + Skeptic':'Director + Analyst + Skeptic';state.chat.push({me:false,txt:'Director ha preso in carico la richiesta. Team: '+team+'. Parto con analisi, verifica e sintesi.'});state.tasks.unshift({id:Date.now(),title:txt.slice(0,70),agent:mode.value==='builder'?'Builder':mode.value==='analyst'?'Analyst':mode.value==='sentinel'?'Sentinel':'Director',status:'working',p:8});if(mode.value==='round'){seedRound();state.round.push({by:'Director',kind:'brief',txt:'Tema proposto da Davide: '+txt});state.view='round'}log('Nuova richiesta: '+txt.slice(0,80));save();render()};
window.newProject=function(){var n=prompt('Nome progetto');if(!n)return;state.projects.unshift({id:Date.now(),name:n,stage:'Discovery',progress:5});log('Creato progetto: '+n);save();render()};window.projectStep=function(id){var p=state.projects.find(function(x){return x.id===id});if(!p)return;p.progress=Math.min(100,p.progress+10);p.stage=p.progress>=100?'Done':'Build';log('Milestone progetto: '+p.name);save();render()};
window.roundTurn=function(){state.round.push({by:'Wildcard',kind:'idea',txt:'Propongo una strada alternativa che riduce dipendenze e complessità.'},{by:'Skeptic',kind:'dissent',txt:'Dissenso: prima di scegliere serve una prova sul caso peggiore.'},{by:'Director',kind:'synthesis',txt:'Sintesi: teniamo la soluzione principale, ma con fallback e checkpoint.'});log('Tavola Rotonda: secondo giro');save();render()};window.humanRound=function(){var e=document.getElementById('roundHuman'),t=(e.value||'').trim();if(!t)return;state.round.push({by:'Davide',kind:'human',txt:t});log('Intervento umano in Tavola Rotonda');save();render()};window.roundDecision=function(){state.round.push({by:'Director',kind:'verify',txt:'Decisione: procedere per step verificabili con controllo umano nei passaggi chiave.'});state.tasks.unshift({id:Date.now(),title:'Eseguire decisione Tavola Rotonda',agent:'Director',status:'working',p:5});log('Decisione Tavola Rotonda trasformata in task');save();render();toast('Decisione trasformata in task')};
window.toggleAgent=function(id){var a=getAgent(id);a.on=!a.on;log((a.on?'Attivato ':'Disattivato ')+a.name);save();render()};window.setProvider=function(id,v){var a=getAgent(id);a.provider=v;log('Provider '+a.name+': '+v);save()};window.addAgent=function(){var n=prompt('Nome agente');if(!n)return;var r=prompt('Ruolo','Specialista')||'Specialista';state.agents.push({id:'custom'+Date.now(),emoji:'🦝',name:n,role:r,provider:'Auto',on:true});log('Aggiunto agente '+n);save();render()};
window.newNote=function(){var t=prompt('Titolo nota');if(!t)return;var b=prompt('Contenuto')||'';state.notes.unshift({id:Date.now(),title:t,body:b});log('Creata nota: '+t);save();render()};window.deleteNote=function(id){state.notes=state.notes.filter(function(n){return n.id!==id});save();render()};window.newEvent=function(){var t=prompt('Evento');if(!t)return;var w=prompt('Quando','Oggi · 16:00')||'Da definire';state.events.unshift({id:Date.now(),when:w,title:t});log('Creato evento: '+t);save();render()};window.removeEvent=function(id){state.events=state.events.filter(function(e){return e.id!==id});save();render()};
function download(name,obj){var b=new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(function(){URL.revokeObjectURL(u)},500)}window.exportAudit=function(){download('the-office-audit.json',state.audit)};window.exportResult=function(id){download('the-office-result.json',state.results.find(function(x){return x.id===id})||{})};window.resetOffice=function(){if(!confirm('Resettare lo stato locale?'))return;state=clone(BASE);state.agents=clone(AGENTS);state.view='home';save();render()};
document.getElementById('themeBtn').onclick=function(){document.body.style.filter=document.body.style.filter?'':'saturate(.9) brightness(.94)';toast('Tema aggiornato')};document.getElementById('globalSearch').addEventListener('keydown',function(e){if(e.key!=='Enter')return;var q=this.value.toLowerCase();if(q.indexOf('tavola')>=0)go('round');else if(q.indexOf('agent')>=0)go('agents');else if(q.indexOf('progett')>=0)go('projects');else if(q.indexOf('know')>=0)go('knowledge');else{go('chat');setTimeout(function(){var x=document.getElementById('chatInput');if(x)x.value=q},20)}});
render();
})();